---
name: Build container image
on:
  schedule:
    - cron: '20 4 * * *'  # Runs at 04:20 UTC every day
  workflow_dispatch:
    inputs:
      install_flathub:
        description: "Flathub"
        required: false
        default: true
        type: boolean
      install_gimp:
        description: "GIMP"
        required: false
        default: false
        type: boolean
      install_kdeapps:
        description: "KDE Apps"
        required: false
        default: true
        type: boolean
      install_libreoffice:
        description: "LibreOffice"
        required: false
        default: false
        type: boolean
      # install_nomachine:
      #   description: "NoMachine"
      #   required: false
      #   default: false
      #   type: boolean
      install_rpmfusion:
        description: "RPM Fusion"
        required: false
        default: true
        type: boolean
      install_qemu:
        description: "QEmu"
        required: false
        default: true
        type: boolean
      install_sunshine:
        description: "Sunshine"
        required: false
        default: true
        type: boolean
      install_thunderbird:
        description: "Thunderbird"
        required: false
        default: true
        type: boolean
      install_vlc:
        description: "VLC"
        required: false
        default: true
        type: boolean
      # install_wine:
      #   description: "Wine"
      #   required: false
      #   default: false
      #   type: boolean

env:
  IMAGE_DESC: "HorizonOS - Customized Fedora Kinoite Image"
  IMAGE_KEYWORDS: "bootc,fedora, kinoite,atomic"
  IMAGE_LOGO_URL: "https://horizon-os.itotm.org/logo.png"
  IMAGE_NAME: "${{ github.event.repository.name }}"
  IMAGE_REGISTRY: "ghcr.io/${{ github.repository_owner }}"
  DEFAULT_TAG: "latest"
  DEFAULT_FEDORA: "43"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_push:
    name: Build and push image
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Prepare environment
        run: |
          # Lowercase the image uri
          echo "IMAGE_REGISTRY=${IMAGE_REGISTRY,,}" >> ${GITHUB_ENV}
          echo "IMAGE_NAME=${IMAGE_NAME,,}" >> ${GITHUB_ENV}

      # These stage versions are pinned by https://github.com/renovatebot/renovate
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      # You only use this action if the container-storage-action proves to be unreliable, you don't need to enable both
      # This is optional, but if you see that your builds are way too big for the runners, you can enable this by uncommenting the following lines:
      - name: Maximize build space
        uses: ublue-os/remove-unwanted-software@695eb75bc387dbcd9685a8e72d23439d8686cba6

      #- name: Mount BTRFS for podman storage
      #  id: container-storage-action
      #  uses: ublue-os/container-storage-action@911baca08baf30c8654933e9e9723cb399892140

        # Fallback to the remove-unwanted-software-action if github doesn't allocate enough space
        # See: https://github.com/ublue-os/container-storage-action/pull/11
      #  continue-on-error: true 
      #  with:
      #    target-dir: /var/lib/containers
      #    mount-opts: compress-force=zstd:1

      - name: Get current date and version
        id: date
        run: |
          # This generates a timestamp like what is defined on the ArtifactHub documentation
          # E.G: 2022-02-08T15:38:15Z'
          # https://artifacthub.io/docs/topics/repositories/container-images/
          # https://linux.die.net/man/1/date
          echo "date=$(date -u +%Y\-%m\-%d\T%H\:%M\:%S\Z)" >> $GITHUB_OUTPUT
          
          # Generate version in format vAAAAMMGG.build
          BUILD_DATE=$(date -u +%Y%m%d)
          BUILD_NUMBER=${{ github.run_number }}
          VERSION="v${BUILD_DATE}.${BUILD_NUMBER}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      # Image metadata for https://artifacthub.io/ - This is optional but is highly recommended so we all can get a index of all the custom images
      # The metadata by itself is not going to do anything, you choose if you want your image to be on ArtifactHub or not.
      - name: Image Metadata
        uses: docker/metadata-action@318604b99e75e41977312d83839a89be02ca4893 # v5
        id: metadata
        with:
          # This generates all the tags for your image, you can add custom tags here too!
          # Default tags are "$DEFAULT_TAG" and version tag in format vAAAAMMGG.build.
          tags: |
            type=raw,value=${{ env.DEFAULT_TAG }}
            type=raw,value=${{ steps.date.outputs.version }}
            type=raw,value=${{ env.DEFAULT_TAG }}.{{date 'YYYYMMDD'}}
            type=raw,value={{date 'YYYYMMDD'}}
            type=raw,value=f${{ env.DEFAULT_FEDORA }}
            type=sha,enable=${{ github.event_name == 'pull_request' }}
            type=ref,event=pr
          labels: |
            io.artifacthub.package.readme-url=https://raw.githubusercontent.com/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}/${{ github.sha }}/README.md
            org.opencontainers.image.created=${{ steps.date.outputs.date }}
            org.opencontainers.image.description=${{ env.IMAGE_DESC }}
            org.opencontainers.image.documentation=https://raw.githubusercontent.com/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}/${{ github.sha }}/README.md
            org.opencontainers.image.source=https://github.com/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}/blob/${{ github.sha }}/Containerfile
            org.opencontainers.image.title=${{ env.IMAGE_NAME }}
            org.opencontainers.image.url=https://github.com/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}/tree/${{ github.sha }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.version=${{ steps.date.outputs.version }}
            io.artifacthub.package.deprecated=false
            io.artifacthub.package.keywords=${{ env.IMAGE_KEYWORDS }}
            io.artifacthub.package.license=Apache-2.0
            io.artifacthub.package.logo-url=${{ env.IMAGE_LOGO_URL }}
            io.artifacthub.package.prerelease=false
            containers.bootc=1
          sep-tags: " "
          sep-annotations: " "

      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@7a95fa7ee0f02d552a32753e7414641a04307056 # v2
        with:
          containerfiles: |
            ./Containerfile
          # Postfix image name with -custom to make it a little more descriptive
          # Syntax: https://docs.github.com/en/actions/learn-github-actions/expressions#format
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          build-args: |
            BUILD_NUMBER=${{ github.run_number }}
            INSTALL_FLATHUB=${{ github.event.inputs.install_flathub }}
            INSTALL_GIMP=${{ github.event.inputs.install_gimp }}
            INSTALL_KDEAPPS=${{ github.event.inputs.install_kdeapps }}
            INSTALL_LIBREOFFICE=${{ github.event.inputs.install_libreoffice }}
            INSTALL_RPMFUSION=${{ github.event.inputs.install_rpmfusion }}
            INSTALL_SUNSHINE=${{ github.event.inputs.install_sunshine }}
            INSTALL_THUNDERBIRD=${{ github.event.inputs.install_thunderbird }}
            INSTALL_VLC=${{ github.event.inputs.install_vlc }}
          layers: true
          oci: false

      # These `if` statements are so that pull requests for your custom images do not make it publish any packages under your name without you knowing
      # They also check if the runner is on the default branch so that things like the merge queue (if you enable it), are going to work
      - name: Login to GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push To GHCR
        uses: redhat-actions/push-to-registry@5ed88d269cf581ea9ef6dd6806d01562096bee9c # v2
        if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        id: push
        env:
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ github.token }}
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ steps.metadata.outputs.tags }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}

      # This section is optional and only needs to be enabled if you plan on distributing
      # your project for others to consume. You will need to create a public and private key
      # using Cosign and save the private key as a repository secret in Github for this workflow
      # to consume. For more details, review the image signing section of the README.
      - name: Install Cosign
        uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4.0.0
        if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)

      - name: Sign container image
        if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        run: |
          IMAGE_FULL="${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}"
          for tag in ${{ steps.metadata.outputs.tags }}; do
            cosign sign -y --key env://COSIGN_PRIVATE_KEY $IMAGE_FULL:$tag
          done
        env:
          TAGS: ${{ steps.push.outputs.digest }}
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}